apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wordpress.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: WORDPRESS_DB_HOST
            value: {{ .Values.env.DATABASEHOST }}
          - name: WORDPRESS_DB_USER
            value: {{ .Values.env.DATABASEUSER }}
          - name: WORDPRESS_DB_PASSWORD
            value: {{ .Values.env.DATABASEPASSWORD }}
          - name: WORDPRESS_DB_NAME
            value: {{ .Values.env.DATABASENAME }}
          volumeMounts:
          - name: {{ .Chart.Name }}-pvc-wp
            mountPath: {{ .Values.path.mountPath }}
            subPath: {{ .Values.path.subPath }}
      volumes:
      - name: {{ .Chart.Name }}-pvc-wp
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-pvc

