name: project-pipeline

on:
  push:
    branches: [ "master" ]
    path:
      - 'docker/**'
  workflow_dispatch:

jobs:
  build:
    name: ci-cd project
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          
      - name: "Hadolint"
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: "./docker/Dockerfile"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          push: true
          tags: getmanovich7/wordpress:${{ steps.tag_version.outputs.new_tag }}
          
      - name: set up Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          
      - name: helm-check
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./helm-source/wordpress
          CHART_VALUES: ./helm-source/wordpress/values.yaml   
      
      - name: Publish Helm charts
        run: |
          cd helm-source/
          helm package wordpress --version=${{ steps.tag_version.outputs.new_tag }} --app-version=${{ steps.tag_version.outputs.new_tag }}
          mv wordpress-v* ../helm-release
          cd ..
          helm repo index --url https://vitaliget.github.io/myproject/ --merge index.yaml .
     
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Publish wordpress:${{ steps.tag_version.outputs.new_tag }}"
          git push origin master

      - name: Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: myproject
          SLACK_COLOR: 'green'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Success'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: gitAction
          SLACK_WEBHOOK: ${{ secrets.WEBHOOK }}
